#  TV workspaces

workspace 1 output $tv
workspace 2 output $tv 
workspace 3 output $tv
workspace 4 output $tv
workspace 5 output $tv

# Laptop workspaces

workspace 6 output $lap
workspace 7 output $lap
workspace 8 output $lap
workspace 9 output $lap
workspace 10 output $lap

